### ISSUE TITLE
Unable to Publish Message into Cluster

### ISSUE THREAD

**Issue by danudell-trustnetworks** [uber/cherami-server#271]
Could do with a hand debugging this.

I have a K8s cluster of 5 containers machines, each ran with --all. They are all talking to each other, and I can create a destination and consumer and verify each host can see it.

However when trying to publish I get the following error:

`Error resolving input hosts: tchannel error ErrCodeUnexpected: InternalServiceError({Message:Nil result, nil error})  dstPth="/foo/bar"`

And in the logs I see:

`time="2017-08-10T13:41:26Z" level=error msg="ReadPublisherOptions: No hosts returned from controller" deploymentName= destID=fa02b132-1ba2-4e75-b867-469f4f172f69 dstPth="/foo/bar" err=<nil> frntID=5e95a39c`

Any help with what to look at next? 

I've restarted the nodes, and I could publish and subscribe for a time, and then the cli disconnected from the inputhost and the same issue happened.

**Comment by danudell-trustnetworks** [comment]
An update -  an hour or so after deployment the logs contains this every couple of minutes:

```
time="2017-08-11T05:33:44Z" level=error msg="No hearts beating. Dumping hearts." deploymentName= maxAllowedAge=1224 outhID=398d8aee
time="2017-08-11T05:33:44Z" level=error msg="KILLING SELF: No hearts have beat" deploymentName= hearts=0 outhID=398d8aee since="2017-08-11T05:13:20Z"
```

this follows some more errors that seem to have gone away:

```
time="2017-08-11T02:25:00Z" level=error msg="thriftClients: error resolving storehost" err="Cannot find ip:port corresponding to uuid" storID=3b53ce6a-1796-456b-81cd-f3314615ba53
time="2017-08-11T02:25:00Z" level=error msg="computeRetention: softRetention GetAddressFromTimestamp error" ctrlID=3c667c38 deploymentName= destID=d0c3c4f8-1990-45f5-a295-47f88fa656e8 err="error resolving storehost 3b53ce6a-1796-456b-81cd-f3314615ba53: Cannot find ip:port corresponding to uuid" extnID=94fa8ce7-c89b-4d14-bc01-d017a685351c module=retMgr softRetentionTime=1502331900894282770 storID=3b53ce6a-1796-456b-81cd-f3314615ba53 worker=1
```

**Comment by danudell-trustnetworks** [comment]
Just for anyone else bumbling through getting s simple cherami cluster going - This was dues to disk space. Theres a default min-space set to something like 30/40gb, which was bigger than the disks I was attaching to my containers. After a while the self monitoring kicks in, see that a store host is past the threshold and removes the store.

This setting can be customised with:

```
  cherami-controllerhost:
    StorePlacementConfig:
      MinFreeDiskSpaceBytes: 10000000000
```

**Comment by cloudsugar** [comment]
my cluster still get the error but no others error, could you show your config to me here?
thanks!
